image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn package
  only:
    changes:
      - src/**/*
  artifacts:
    paths:
      - target/Habbo-*.jar

.notify_builder: &notify_builder
  stage: deploy
  trigger:
    project: project-dobby/builder
    strategy: depend

notify_deploy_release:
  <<: *notify_builder
  variables:
    UPSTREAM_DECISION: "tag"
    UPSTREAM_COMMIT_SHA: $CI_COMMIT_SHA
    UPSTREAM_PROJECT: $CI_PROJECT_PATH
    UPSTREAM_BRANCH: $CI_COMMIT_TAG
  only:
    - tags

notify_deploy_dev:
  <<: *notify_builder
  variables:
    UPSTREAM_DECISION: "dev" 
    UPSTREAM_COMMIT_SHA: $CI_COMMIT_SHA
    UPSTREAM_PROJECT: $CI_PROJECT_PATH
    UPSTREAM_BRANCH: "dev"
  only:
    - dev
  