image: maven:latest

stages:
  - build
  - deploy

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn package
  only:
    - dev
    - master
  artifacts:
      paths:
      - target/Habbo-*.jar
  
